# only fluentd
# <source>
#   @type forward
#   port 24224
#   bind 0.0.0.0
# </source>

# # Match all Docker logs
# <match **>
#   @type copy
#   <store>
#     # Output to console (for docker-compose logs)
#     @type stdout
#     <format>
#       @type json
#     </format>
#   </store>
#   <store>
#     # Save to file
#     @type file
#     path /fluentd/log/docker.*.log
#     symlink_path /fluentd/log/docker.log
#     append true
#     <format>
#       @type json
#     </format>
#   </store>
# </match>

# with loki:
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

# Filter only app logs (not fluentd own logs)
<filter app.**>
  @type record_transformer
  <record>
    hostname "#{Socket.gethostname}"
    tag ${tag}
  </record>
</filter>

# Send to both file and Loki
<match app.**>
  @type copy
  # <store>                                                                       --> this store for local store
  #   @type file
  #   path /fluentd/log/docker.*.log
  #   symlink_path /fluentd/log/docker.log
  #   append true
  #   <format>
  #     @type json
  #   </format>
  #   <buffer>
  #     @type file
  #     path /fluentd/log/buffer
  #     flush_interval 2s
  #   </buffer>
  # </store>
  <store>
    @type loki
    url "http://loki:3100"
    <label>
      container_name
      source
    </label>
    <buffer>
      @type memory
      flush_interval 2s
    </buffer>
  </store>
</match>